### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/polling#10]
Add a favicon to project, to call attention from users and to be correspond with context of site, about polls.

Today the app is without favicon:
![image](https://user-images.githubusercontent.com/9089383/32150623-6c72e0fc-bcfc-11e7-93af-1259021dd2d9.png)

**Comment by lantran** [comment]
Hi Roberto,

I would like to work on this.

**Comment by robertoduessmann** [comment]
Thanks for contributing with project @lantran :rocket:
