### ISSUE TITLE
Validation to not use spaces in poll name

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/polling#12]
The name input must have only letters or number, are not permitted spaces, because it used in redirect.

Create a validation to not permit users create a poll with a name with spaces:
![image](https://user-images.githubusercontent.com/9089383/32151484-5fbd1780-bd04-11e7-8f83-76443654ef93.png)

**Comment by lantran** [comment]
Hi Roberto, I will work on this

**Comment by robertoduessmann** [comment]
https://github.com/robertoduessmann/polling/pull/21
