### ISSUE TITLE
 Alert Message in Name Field

### ISSUE THREAD

**Issue by lycan-nt** [robertoduessmann/polling#27]
When trying to name the question, it does not accept space.
EX: Where are we going to lunch? > give alert message

**Comment by robertoduessmann** [comment]
Hey @lycan-nt , thanks for your feedback.
The name works like a code, once it will be part of the URL (i.e lunch: https://decideja.herokuapp.com/lunch). The proper question can be placed in the second field.
However I don't think it's clear enought, I'll keep the issue open to we improve it, I would suggest to change the "Name" field to "Code" to make clearer it's about the polling code, what do you think?

**Comment by lycan-nt** [comment]
@robertoduessmann 

I understood, code would be much clearer.

Now wouldn't identifier be simpler? and then in the text field, for example, appears a question identifier: lunch

**Comment by robertoduessmann** [comment]
Hey @lycan-nt , that's also would be a valid option.

I just updated it to Code to we check if looks better, could you have a quick look, I would love hear your feedback :smile:

**Comment by lycan-nt** [comment]
Great, congratulations. Do you think of a field to search for suggestions created?

**Comment by robertoduessmann** [comment]
Hey @lycan-nt o this would be nice actually, didn't think about it yet, feel free to create an issue/pull request with the suggestion, would love to see it :smile:
