### ISSUE TITLE
Update year's footer

### ISSUE THREAD

**Issue by robertoduessmann** [robertoduessmann/polling#30]
As I user I would like to have the updated year in my footer`s page:

![image](https://user-images.githubusercontent.com/9089383/67076873-5712a300-f18e-11e9-9d11-608897abd294.png)

Would be nice load it dynamically.

**Comment by 5aint2ero** [comment]
do you want it like: c <actual year> ?
(already proposed a solution)

**Comment by Chirag175** [comment]
I've submitted a client-based JavaScript solution: https://github.com/robertoduessmann/polling/pull/32. Please take a look at it and if there are any changes to be made, I'd like to be informed.

**Comment by robertoduessmann** [comment]
Thanks @5aint2ero closed #31 
I just have to changed it to the js, once the meteor couldn't recognize the <script> tag.

Thanks for the interesting btw @Chirag175 , really appreciate it too :)
